services:
  frontend_seed:
    container_name: frontend_seed
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3080:5173"
    volumes:
      - ./src:/app/src
    networks:
      - marathon_network

networks:
  marathon_network:
    driver: bridge