FROM node:24.15.0

WORKDIR /app

RUN --mount=type=cache,id=corepack,target=/root/.cache/node/corepack \
    corepack enable && corepack prepare pnpm@10.17.1 --activate

ENV NODE_ENV=local

COPY src/package.json src/pnpm-lock.yaml* ./
COPY src/tsconfig.json ./

RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store \
    pnpm install

COPY src/src ./src
COPY src/.env .env
COPY src/knexfile.ts ./

CMD ["pnpm", "run", "dev"]
